This is an automated email generated by the Tabula system.

You have now been assigned as personal tutor to ${tutee.officialName}, whose student profile can be found at <@url page='${path}'/>.

(Replies to this email will not reach a real person.)
