This is an automated email generated by the Tabula system.

You have now been assigned as personal tutor to ${tutee.officialName}.  The previous tutor was ${oldTutor.officialName}.

(Replies to this email will not reach a real person.)
