This is an automated email generated by the Tabula system.

Your tutee ${tutee.officialName} has now been reassigned to ${newTutor.officialName}.

(Replies to this email will not reach a real person.)
