This is an automated email generated by the Tabula system.

Your tutee ${tutee.officialName} has now been reassigned to ${newTutor.officialName}.

The student profile for ${tutee.officialName} can be found at <@url page='${path}'/>.

(Replies to this email will not reach a real person.)
