This is an automated email generated by the Tabula system.
	          
Your personal tutor has been changed from ${oldTutor.officialName} to ${newTutor.officialName}.

(Replies to this email will not reach a real person.)
