This is an automated email generated by the Tabula system.
	          
Your personal tutor has been changed from ${oldTutor.officialName} to ${newTutor.officialName}.  
You can view this on your student profile page at <@url page='${path}'/>.

(Replies to this email will not reach a real person.)
