This is an automated email generated by the Tabula system.

<#if oldTutor??>
Your personal tutor has been changed from ${oldTutor.officialName} to ${newTutor.officialName}.
<#else>
You have been assigned ${newTutor.officialName} as a personal tutor.
</#if>

You can view this information on your student profile page at <@url page='${path}'/>.

(Replies to this email will not reach a real person.)
