package uk.ac.warwick.tabula.lucene

object Synonyms {
	
	// TODO this is so very rubbish
	// Collected from http://search.warwick.ac.uk/search/admin/editNameSynonyms.html 13/12/12
	val names = Map(
		"alan" -> Set("allan"),
		"allan" -> Set("alan"),
		"amanda" -> Set("mandy"),
		"andrew" -> Set("andy"),
		"andy" -> Set("andrew"),
		"becky" -> Set("rebecca"),
		"bill" -> Set("william"),
		"billy" -> Set("bill", "william"),
		"bob" -> Set("robert", "rob"),
		"cath" -> Set("katherine"),
		"catherine" -> Set("katherine", "cath"),
		"charles" -> Set("charlie"),
		"charlie" -> Set("charles"),
		"christina" -> Set("christine", "tina"),
		"christine" -> Set("christina", "tina"),
		"christopher" -> Set("chris"),
		"claire" -> Set("clare"),
		"clare" -> Set("claire"),
		"daniel" -> Set("danny", "dan"),
		"danielle" -> Set("danny"),
		"danny" -> Set("dan", "daniel", "danielle"),
		"dave" -> Set("david"),
		"david" -> Set("dave"),
		"debbie" -> Set("debby", "deb", "debra", "deborah"),
		"debby" -> Set("debbie", "deb", "debra", "deborah"),
		"deborah" -> Set("debbie", "debby", "deb", "debra"),
		"debra" -> Set("debbie", "debby", "deb", "deborah"),
		"dick" -> Set("richard"),
		"dorothea" -> Set("dorothy"),
		"dorothy" -> Set("dorothea"),
		"eleanor" -> Set("ellie"),
		"elizabeth" -> Set("liz"),
		"ellie" -> Set("eleanor"),
		"gill" -> Set("jill", "jillian"),
		"gillian" -> Set("gill", "jill", "jillian"),
		"graeme" -> Set("graham"),
		"graham" -> Set("graeme"),
		"gregg" -> Set("greg", "gregory"),
		"gregory" -> Set("greg", "gregg"),
		"hollie" -> Set("holly"),
		"holly" -> Set("hollie"),
		"jackie" -> Set("jacqueline", "jacquie"),
		"jacqueline" -> Set("jackie", "jacquie"),
		"jacquie" -> Set("jackie", "jacqueline"),
		"jaimey" -> Set("james", "jamie", "jamey", "jaimy", "jim", "jimmy"),
		"jaimy" -> Set("james", "jamie", "jamey", "jaimey", "jim", "jimmy"),
		"jaine" -> Set("jane", "jayne"),
		"james" -> Set("jamie", "jamey", "jaimey", "jaimy", "jim", "jimmy"),
		"jamey" -> Set("james", "jamie", "jaimey", "jaimy", "jim", "jimmy"),
		"jamie" -> Set("james", "jamey", "jaimey", "jaimy", "jim", "jimmy"),
		"jane" -> Set("jayne", "jaine"),
		"janet" -> Set("jan"),
		"janette" -> Set("janet", "jan"),
		"jayne" -> Set("jane", "jaine"),
		"jenifer" -> Set("jennifer", "jeniffer", "jenniffer", "jenny", "jennie"),
		"jeniffer" -> Set("jenniffer", "jenifer", "jennifer", "jenny", "jennie"),
		"jennie" -> Set("jenifer", "jennifer", "jeniffer", "jenniffer", "jenny"),
		"jennifer" -> Set("jenniffer", "jenifer", "jeniffer", "jenny", "jennie"),
		"jenniffer" -> Set("jennifer", "jenifer", "jeniffer", "jenny", "jennie"),
		"jenny" -> Set("jenifer", "jennifer", "jeniffer", "jenniffer", "jennie"),
		"jill" -> Set("gill", "gillian"),
		"jillian" -> Set("gillian", "gill", "jill"),
		"jim" -> Set("james", "jamie", "jamey", "jaimey", "jaimy", "jimmy"),
		"jimmy" -> Set("james", "jamie", "jamey", "jaimey", "jaimy", "jim"),
		"john" -> Set("jon", "jonathan"),
		"jon" -> Set("john", "johnathan"),
		"julia" -> Set("julie"),
		"julie" -> Set("julia"),
		"justina" -> Set("justine", "tina"),
		"justine" -> Set("justina", "tina"),
		"kate" -> Set("katie"),
		"katherine" -> Set("cath", "catherine"),
		"katie" -> Set("kate"),
		"kenneth" -> Set("ken"),
		"lewellyn" -> Set("lewelyn", "llewelyn", "llewellyn"),
		"lewelyn" -> Set("lewellyn", "llewelyn", "llewellyn"),
		"liz" -> Set("elizabeth"),
		"llewellyn" -> Set("lewellyn", "llewelyn", "lewelyn"),
		"llewelyn" -> Set("lewellyn", "lewelyn", "llewellyn"),
		"mandy" -> Set("amanda"),
		"mathew" -> Set("matthew"),
		"mathews" -> Set("matthews"),
		"matt" -> Set("mathew", "mat"),
		"matthew" -> Set("mathew"),
		"matthews" -> Set("mathews"),
		"michael" -> Set("mike"),
		"michele" -> Set("michelle"),
		"michelle" -> Set("michele"),
		"mike" -> Set("michael"),
		"nicholas" -> Set("nick", "nicolas"),
		"nick" -> Set("nicholas", "nicolas"),
		"nicolas" -> Set("nicholas", "nick"),
		"patricia" -> Set("pat"),
		"patrick" -> Set("pat"),
		"penelope" -> Set("penny"),
		"penny" -> Set("penelope"),
		"peter" -> Set("pete"),
		"philip" -> Set("phillip", "phil"),
		"philipa" -> Set("phillipa", "phillippa", "philippa", "pippa"),
		"philippa" -> Set("philipa", "phillippa", "phillipa", "pippa"),
		"phillip" -> Set("philip", "phil"),
		"phillipa" -> Set("philipa", "phillippa", "philippa", "pippa"),
		"phillippa" -> Set("philipa", "phillipa", "philippa", "pippa"),
		"pippa" -> Set("philipa", "phillippa", "phillipa", "philippa"),
		"rebecca" -> Set("becky"),
		"richard" -> Set("dick", "dickie"),
		"rob" -> Set("bob"),
		"robert" -> Set("bob", "rob"),
		"robin" -> Set("robyn"),
		"robyn" -> Set("robin"),
		"sarah" -> Set("sara"),
		"shane" -> Set("shayne"),
		"shayne" -> Set("shane"),
		"stephen" -> Set("steven"),
		"steve" -> Set("stephen"),
		"steven" -> Set("stephen", "steve"),
		"sue" -> Set("susannah", "susanna", "suzannah", "suzanna", "suzi", "suzie", "susan", "suzan"),
		"susan" -> Set("suzannah", "suzanna", "susanna", "susannah", "sue", "suzi", "suzan"),
		"suzan" -> Set("suzannah", "suzanna", "susanna", "susannah", "sue", "suzi", "susan"),
		"suzanna" -> Set("suzi", "suzie", "susanna", "susannah", "sue", "susan", "suzan"),
		"suzannah" -> Set("suzanna", "suzi", "suzie", "susanna", "sue", "susan", "suzan"),
		"suzi" -> Set("suzannah", "suzanna", "susanna", "susannah", "sue", "susan", "suzan"),
		"suzie" -> Set("suzi", "suzannah", "suzanna", "susannah", "susanna", "sue", "susan", "suzan"),
		"thomas" -> Set("tom"),
		"tina" -> Set("christine", "christina", "justine", "justina"),
		"tom" -> Set("thomas"),
		"wahlberg" -> Set("wahlburg"),
		"wahlburg" -> Set("wahlberg"),
		"william" -> Set("bill", "billy")			
	)
}