CREATE TABLE ORIGINALITYREPORT (
	ID NVARCHAR2(100) NOT NULL,
	SUBMISSION_ID NVARCHAR2(100) NOT NULL,
	
	CREATEDDATE TIMESTAMP NOT NULL,
	
	SIMILARITY NUMBER(3,0),
	OVERLAP NUMBER(3,0),
	STUDENT_OVERLAP NUMBER(3,0),
	WEB_OVERLAP NUMBER(3,0),
	PUBLICATION_OVERLAP NUMBER(3,0),
	
	CONSTRAINT "ORIGINALITYRPT_PK" PRIMARY KEY ("ID")
);
CREATE INDEX "IDX_ORIGINALITYRPT_SUBMISSION" ON ORIGINALITYREPORT("SUBMISSION_ID");