-- HFC-33

CREATE TABLE UPSTREAMASSIGNMENT (
	ID NVARCHAR2(100) NOT NULL,
	MODULECODE NVARCHAR2(100) NOT NULL,
	ASSESSMENTGROUP NVARCHAR2(100) NOT NULL,
	SEQUENCE NVARCHAR2(100) NOT NULL,
	DEPARTMENTCODE NVARCHAR2(10) NOT NULL,
	NAME NVARCHAR2(4000) NOT NULL,
	CONSTRAINT "UPSTREAMASSIGNMENT_PK" PRIMARY KEY ("ID")
);
CREATE UNIQUE INDEX UPSTREAMASSIGNMENT_MAIN_IDX ON UPSTREAMASSIGNMENT(MODULECODE, SEQUENCE);
CREATE INDEX UPSTREAMASSIGNMENT_DEPT_IDX ON UPSTREAMASSIGNMENT(DEPARTMENTCODE);

CREATE TABLE UPSTREAMASSESSMENTGROUP (
	MODULECODE NVARCHAR2(100) NOT NULL,
	ASSESSMENTGROUP NVARCHAR2(100) NOT NULL,
	ACADEMICYEAR NUMBER(4,0) NOT NULL,
	OCCURENCE NVARCHAR2(100) NOT NULL,
	MEMBERSGROUP_ID NVARCHAR2(4000),
	CONSTRAINT "UPSTREAMASSESSMENTGROUP_PK" PRIMARY KEY ("ID")
);
CREATE INDEX UPSTREAMASSESSMENTGROUP_YEAR_IDX ON UPSTREAMASSESSMENTGROUP(ACADEMICYEAR);

CREATE TABLE USERGROUPSTATIC (
    group_id nvarchar2(255) not null,
    usercode nvarchar2(255)
);

ALTER TABLE USERGROUP ADD UNIVERSITYIDS NUMBER(1,0) DEFAULT 0; 