-- SBTWO-68 Jobs

CREATE TABLE JOB (
	ID NVARCHAR2(100) NOT NULL,
	
	JOBTYPE NVARCHAR2(100) NOT NULL,
	STATUS NVARCHAR2(4000),
	DATA CLOB NOT NULL,
	STARTED NUMBER(1,0) DEFAULT 0 NOT NULL,
	FINISHED NUMBER(1,0) DEFAULT 0 NOT NULL,
	SUCCEEDED NUMBER(1,0) DEFAULT 0 NOT NULL,
	PROGRESS NUMBER(3,0),
	
	CREATEDDATE TIMESTAMP NOT NULL,
	UPDATEDDATE TIMESTAMP NOT NULL,
	
	CONSTRAINT "JOB_PK" PRIMARY KEY ("ID")
);
CREATE INDEX "IDX_JOBSTARTED" ON JOB("STARTED","FINISHED");


ALTER TABLE JOB ADD ( REALUSER NVARCHAR2(255) );
ALTER TABLE JOB ADD ( APPARENTUSER NVARCHAR2(255) );

