
-- HFC-34

ALTER TABLE ASSIGNMENT  
ADD (COLLECTSUBMISSIONS NUMBER(1,0) DEFAULT 0 NOT NULL  );

ALTER TABLE ASSIGNMENT  
ADD (RESTRICTSUBMISSIONS NUMBER(1,0) DEFAULT 0 NOT NULL  );

ALTER TABLE ASSIGNMENT  
ADD (allowLateSubmissions NUMBER(1,0) DEFAULT 1 NOT NULL  );