-- let's make a fake ADS
drop table MODULE_REGISTRATION if exists;
CREATE TABLE MODULE_REGISTRATION 
(
  ACADEMIC_YEAR_CODE VARCHAR(6) NOT NULL 
, ASSESSMENT_GROUP VARCHAR(2) 
, CATS integer
, MAV_OCCURRENCE VARCHAR(6) NOT NULL 
, MODULE_CODE VARCHAR(10) NOT NULL 
, MOD_REG_TYPE_CODE integer 
, REGISTRATION_STATUS integer
, SITS_OR_OMR varCHAR(1) 
, SPR_CODE VARCHAR(12) NOT NULL 
);

insert into module_registration values (
  '11/12','A',30,'A','CH115',1,1,'S','0123456/1'
);
