-- let's make a fake SITS

DROP TABLE CAM_FMC IF EXISTS;

CREATE TABLE CAM_FMC
(
    FMC_CODE VARCHAR(32) PRIMARY KEY NOT NULL,
    FMC_SNAM VARCHAR(15),
    FMC_NAME VARCHAR(120),
    FMC_IUSE VARCHAR(1)
);

DROP TABLE CAM_FME IF EXISTS;

CREATE TABLE CAM_FME
(
    FMC_CODE VARCHAR(32) NOT NULL,
    FME_SEQ VARCHAR(3) NOT NULL,
    FME_MODP VARCHAR(12),
    SCH_CODE VARCHAR(6),
    LEV_CODE VARCHAR(6),
    MTC_CODE VARCHAR(6)
);

INSERT INTO CAM_FMC VALUES ('A100-1-14-CAA', null, null, 'Y');
INSERT INTO CAM_FMC VALUES ('B100-1-14-CAA', null, null, 'Y');
INSERT INTO CAM_FMC VALUES ('A100-A-14-CAA', null, null, 'Y');
INSERT INTO CAM_FMC VALUES ('A100-1-AA-CAA', null, null, 'Y');

INSERT INTO CAM_FME VALUES ('A100-1-14-CAA', '01', '*', null, null, null)
INSERT INTO CAM_FME VALUES ('A100-1-14-CAA', '02', 'CH?00*', null, null, null)
INSERT INTO CAM_FME VALUES ('A100-1-14-CAA', '03', 'CH100-7.5', null, null, null)