-- HFC-363

CREATE TABLE MARKSCHEME
(
  ID NVARCHAR2(255) NOT NULL
, NAME NVARCHAR2(255) NOT NULL
, DEPARTMENT_ID NVARCHAR2(255)
, FIRSTMARKERS_ID NVARCHAR2(255)
, SECONDMARKERS_ID NVARCHAR2(255)
, CONSTRAINT MARKSCHEME_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

-- WHOOPS forgot this column
ALTER TABLE MARKSCHEME 
ADD ( STUDENTSCHOOSEMARKER NUMBER(1,0) DEFAULT 0 NOT NULL );

-- WHOOPS these columns are too short
ALTER TABLE MARKSCHEME 
MODIFY ( FIRSTMARKERS_ID NVARCHAR2(255) );
ALTER TABLE MARKSCHEME 
MODIFY ( SECONDMARKERS_ID NVARCHAR2(255) );

ALTER TABLE ASSIGNMENT
ADD (MARKSCHEME_ID NVARCHAR2(255) );

CREATE INDEX IDX_MARKSCHEME_DEPT ON MARKSCHEME (DEPARTMENT_ID);

