-- HFC-237 
ALTER TABLE ORIGINALITYREPORT 
ADD (ATTACHMENT_ID NVARCHAR2(100) );

CREATE INDEX IDX_ORIGINALITYRPT_ATTACH ON ORIGINALITYREPORT (ATTACHMENT_ID);

-- make submission_id nullable since it won't be used. we'll delete it later
ALTER TABLE ORIGINALITYREPORT  
MODIFY (SUBMISSION_ID NULL);
