CREATE TABLE SUBMISSIONVALUE (
	id nvarchar2(100) not null,
	name nvarchar2(255) not null,
	submission_id nvarchar2(255) not null,
	VALUE nvarchar2(4000),
	CONSTRAINT "SUBMISSIONVALUE_PK" PRIMARY KEY ("ID")
);
CREATE INDEX "IDX_SUBMISSIONVALUE_SUBMISSION" ON SUBMISSIONVALUE(SUBMISSION_ID);