-- TAB-582 More indexing for member lookups

CREATE INDEX IDX_MEMBER_DEPT ON MEMBER (HOME_DEPARTMENT_ID);

CREATE INDEX IDX_MEMBER_USERTYPE ON MEMBER (USERTYPE);

CREATE INDEX IDX_STUDYDETAILS_SPRCODE ON STUDYDETAILS (SPRCODE);