-- TAB-358

CREATE TABLE meetingrecord (
	
	ID NVARCHAR2(255) NOT NULL,
	RELATIONSHIP_ID NVARCHAR2(255) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	LAST_UPDATED_DATE TIMESTAMP NOT NULL,
	CREATOR_ID NVARCHAR2(255) NOT NULL,
	MEETING_DATE TIMESTAMP,
	TITLE NVARCHAR2(500),
	DESCRIPTION NCLOB,

  CONSTRAINT "MEETINGRECORD_PK" PRIMARY KEY ("ID")
);

CREATE INDEX IDX_MEETINGS_REL ON MEETINGRECORD ("RELATIONSHIP_ID");