-- TAB-358

CREATE TABLE meetingrecord (
	
	ID NVARCHAR2(382) NOT NULL,
	SPRCODE NVARCHAR2(20) NOT NULL,
	RELATIONSHIPTYPE NVARCHAR2(75) NOT NULL,
	AGENT NVARCHAR2(382) NOT NULL,
  	CREATIONDATE TIMESTAMP NOT NULL,
  	MEETINGDATE TIMESTAMP,
  	LASTUPDATEDDATE TIMESTAMP NOT NULL,
  	TITLE NVARCHAR2(500),
  	PUBLISHER NVARCHAR2(382) NOT NULL,
  	DESCRIPTION NCLOB,
  	
  
	CONSTRAINT "MEETINGRECORD_PK" PRIMARY KEY ("ID")
);
