--- TAB-376
create table USERSETTINGS (
	ID NVARCHAR2(100) NOT NULL,
	
	USERID NVARCHAR2(100) NOT NULL,
	SETTINGS NCLOB,
	
	CONSTRAINT "USERSETTINGS_PK" PRIMARY KEY ("ID")	
);

CREATE INDEX "IDX_USERSETTINGS_USERID" ON USERSETTINGS("USERID");