-- TAB-1029 StudentRelationshipType table

CREATE TABLE STUDENTRELATIONSHIPTYPE (
	ID NVARCHAR2(255) NOT NULL,
	DESCRIPTION NVARCHAR2(20) NOT NULL,
	ACTORROLE NVARCHAR2(20) NOT NULL,
	STUDENTROLE NVARCHAR2(20) NOT NULL,
	DEFAULTSOURCE NVARCHAR2(20) NOT NULL,
  
	CONSTRAINT "STURELTYPE_PK" PRIMARY KEY ("ID")
);

INSERT INTO STUDENTRELATIONSHIPTYPE (ID, DESCRIPTION, ACTORROLE, STUDENTROLE, DEFAULTSOURCE)
VALUES ('tutor', 'Personal Tutor', 'personal tutor', 'personal tutee', 'local');

INSERT INTO STUDENTRELATIONSHIPTYPE (ID, DESCRIPTION, ACTORROLE, STUDENTROLE, DEFAULTSOURCE)
VALUES ('supervisor', 'Research Supervisor', 'supervisor', 'supervisee', 'sits');