-- TAB-579 Course table

CREATE TABLE COURSE (
	
	CODE NVARCHAR2(20) NOT NULL,
	SHORTNAME NVARCHAR2(20),
	NAME NVARCHAR2(100),
	TITLE NVARCHAR2(200),
  	LASTUPDATEDDATE TIMESTAMP,
  
	CONSTRAINT "COURSE_PK" PRIMARY KEY ("CODE")
);

