-- TAB-579 Course table

CREATE TABLE AWARD (
	
	CODE NVARCHAR2(20) NOT NULL,
	SHORTNAME NVARCHAR2(20),
	NAME NVARCHAR2(100),

  	LASTUPDATEDDATE TIMESTAMP,
  
	CONSTRAINT "AWARD_PK" PRIMARY KEY ("CODE")
);

