ALTER TABLE SmallGroupSet ADD OPEN_FOR_SIGNUPS NUMBER(1, 0);

UPDATE SmallGroupSet SET OPEN_FOR_SIGNUPS = 0 where OPEN_FOR_SIGNUPS IS NULL;

ALTER TABLE SmallGroupSet MODIFY (OPEN_FOR_SIGNUPS DEFAULT 0);

