create index IDX_SCD_ROUTE on STUDENTCOURSEDETAILS("ROUTECODE");
create index IDX_SCD_SPR_STATUS on STUDENTCOURSEDETAILS("SPRSTATUSCODE");
create index IDX_SCYD_MOA on STUDENTCOURSEYEARDETAILS("MODEOFATTENDANCECODE");
create index IDX_SCYD_YEAR on STUDENTCOURSEYEARDETAILS("YEAROFSTUDY");
create index IDX_MODREG_MODULE on MODULEREGISTRATION("MODULECODE");