-- TAB-1029 StudentRelationshipType table

CREATE TABLE STUDENTRELATIONSHIPTYPE (
	ID NVARCHAR2(255) NOT NULL,
	URLPART NVARCHAR2(255) NOT NULL,
	DESCRIPTION NVARCHAR2(50) NOT NULL,
	AGENTROLE NVARCHAR2(50) NOT NULL,
	STUDENTROLE NVARCHAR2(50) NOT NULL,
	DEFAULTSOURCE NVARCHAR2(20) NOT NULL,
	DEFAULTDISPLAY NUMBER(1,0) DEFAULT 1,
	EXPECTED_UG NUMBER(1,0) DEFAULT 0,
	EXPECTED_PGT NUMBER(1,0) DEFAULT 0,
	EXPECTED_PGR NUMBER(1,0) DEFAULT 0,
	SORT_ORDER NUMBER(4, 0) DEFAULT 2,
  
	CONSTRAINT "STURELTYPE_PK" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX IDX_STURELTYPE_URLPART ON STUDENTRELATIONSHIPTYPE(URLPART);

INSERT INTO STUDENTRELATIONSHIPTYPE (ID, URLPART, DESCRIPTION, AGENTROLE, STUDENTROLE, DEFAULTSOURCE, DEFAULTDISPLAY, EXPECTED_UG, EXPECTED_PGT, EXPECTED_PGR, ORDER)
VALUES ('personalTutor', 'tutor', 'Personal Tutor', 'personal tutor', 'personal tutee', 'local', 1, 1, 1, 0, 0);

INSERT INTO STUDENTRELATIONSHIPTYPE (ID, URLPART, DESCRIPTION, AGENTROLE, STUDENTROLE, DEFAULTSOURCE, DEFAULTDISPLAY, EXPECTED_UG, EXPECTED_PGT, EXPECTED_PGR, ORDER)
VALUES ('supervisor', 'supervisor', 'Research Supervisor', 'supervisor', 'supervisee', 'sits', 1, 0, 0, 1, 1);