create table monitoringpointreport (
  ID NVARCHAR2(255) NOT NULL,
  STUDENT NVARCHAR2(100) NOT NULL,
  STUDENT_COURSE_DETAILS_ID NVARCHAR2(20) NOT NULL,
  STUDENT_COURSE_YEAR_DETAILS_ID NVARCHAR2(250) NOT NULL,
  CREATEDDATE TIMESTAMP(6) NOT NULL,
  PUSHEDDATE TIMESTAMP(6) NULL,
  MONITORINGPERIOD NVARCHAR2(100) NOT NULL,
  ACADEMICYEAR NUMBER(4,0) NOT NULL,
  MISSED NUMBER(4,0) NOT NULL,
  REPORTER NVARCHAR2(100) NOT NULL,

  CONSTRAINT "MPR_PK" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX IDX_MPR_STUDENT_PERIOD_YEAR ON monitoringpointreport(STUDENT, MONITORINGPERIOD, ACADEMICYEAR);