ALTER TABLE SmallGroupSet ADD SELF_GROUP_SWITCHING NUMBER(1, 0);

UPDATE SmallGroupSet SET SELF_GROUP_SWITCHING = 0 where SELF_GROUP_SWITCHING IS NULL;

ALTER TABLE SmallGroupSet MODIFY (SELF_GROUP_SWITCHING DEFAULT 0);

-- TAB-920 Now required to default to true
ALTER TABLE SmallGroupSet MODIFY (SELF_GROUP_SWITCHING DEFAULT 1);

UPDATE SmallGroupSet SET SELF_GROUP_SWITCHING = 1;