-- TAB-1959

CREATE TABLE RECIPIENTNOTIFICATIONINFO
(
  ID                NVARCHAR2(255)  NOT NULL,
  NOTIFICATION_ID   NVARCHAR2(255)  NOT NULL,
  RECIPIENT         NVARCHAR2(255)  NOT NULL,
  DISMISSED         NUMBER(1,0)     DEFAULT 0 NOT NULL,
  EMAIL_SENT        NUMBER(1,0)     DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX "IDX_RECIPIENTNOTIFICATION" ON RECIPIENTNOTIFICATIONINFO(NOTIFICATION_ID, RECIPIENT);
ALTER TABLE RECIPIENTNOTIFICATIONINFO ADD CONSTRAINT NOTIFICATION_FK FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATION;