-- TAB-3028 Marks queued for SITS upload

CREATE TABLE FEEDBACKFORSITS (
	ID NVARCHAR2(100) NOT NULL,
  FEEDBACK_ID NVARCHAR2(100) NOT NULL,
  STATUS NVARCHAR2(100),
  FIRSTCREATEDON TIMESTAMP,
  LASTINITIALISEDON TIMESTAMP,
  DATEOFUPLOAD TIMESTAMP,
  ACTUALMARKLASTUPLOADED NUMBER(5),
  ACTUALGRADELASTUPLOADED NVARCHAR2(2),
  INITIALISER NVARCHAR2(250),
  HIB_VERSION NUMBER
);

CONSTRAINT PK_FEEDBACKFORSITS PRIMARY KEY(ID);

CREATE UNIQUE INDEX IDX_FEEDBACKFORSITS_FEEDBACK ON FEEDBACKFORSITS(FEEDBACK_ID);

ALTER TABLE ASSIGNMENT ADD UPLOADMARKSTOSITS NUMBER(1,0) DEFAULT 0 NOT NULL;

ALTER TABLE MODULE ADD DEGREETYPE NVARCHAR2(100);