-- TAB-1929

ALTER TABLE Assignment ADD DISSERTATION Number(1, 0);

UPDATE Assignment SET DISSERTATION = 0 WHERE DISSERTATION Is Null;

Alter Table ASSIGNMENT MODIFY (DISSERTATION Default 0);

ALTER TABLE ASSIGNMENT MODIFY (DISSERTATION NOT NULL);
