-- TAB-3028 Marks queued for SITS upload

CREATE TABLE FEEDBACKFORSITS (
	ID NVARCHAR2(100) NOT NULL,
  FEEDBACK_ID NVARCHAR2(100) NOT NULL,
  STATUS NVARCHAR2(100),
  FIRSTCREATEDON TIMESTAMP,
  LASTINITIALISEDON TIMESTAMP,
  DATEOFUPLOAD TIMESTAMP,
  ACTUALMARKLASTUPLOADED NUMBER(5),
  ACTUALGRADELASTUPLOADED NVARCHAR2(2),
  INITIALISERID NVARCHAR2(250),
  HIB_VERSION NUMBER

);

