-- TAB-2235

CREATE TABLE ATTENDANCEMONITORINGSCHEME (
  ID NVARCHAR2(255) NOT NULL,
  NAME NVARCHAR2(4000),
  ACADEMICYEAR NUMBER(4,0) NOT NULL,
  MEMBERSGROUP_ID NVARCHAR2(255) NOT NULL,
  MEMBER_QUERY NCLOB,
  POINT_STYLE NVARCHAR2(100) NOT NULL,
  DEPARTMENT_ID NVARCHAR2(255) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL,
  UPDATED_DATE TIMESTAMP(6) NOT NULL,

  CONSTRAINT "ATTENDANCEMONITORINGSCHEME_PK" PRIMARY KEY ("ID")
);

CREATE TABLE ATTENDANCEMONITORINGPOINT (
  ID NVARCHAR2(255) NOT NULL,
  SCHEME_ID NVARCHAR2(255) NOT NULL,
  NAME NVARCHAR2(4000) NOT NULL,
  START_WEEK NUMBER(2,0),
  END_WEEK NUMBER(2,0),
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  POINT_TYPE NVARCHAR2(100) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL,
  UPDATED_DATE TIMESTAMP(6) NOT NULL,

  CONSTRAINT "ATTENDANCEMONITORINGPOINT_PK" PRIMARY KEY ("ID")
);

CREATE INDEX ATTENDANCEMONITORINGPOINT_SCHEME_ID ON ATTENDANCEMONITORINGPOINT(SCHEME_ID);

CREATE TABLE ATTENDANCEMONITORINGCHECKPOINT (
  ID NVARCHAR2(255) NOT NULL,
  POINT_ID NVARCHAR2(255) NOT NULL,
  STUDENT_ID NVARCHAR2(100) NOT NULL,
  STATE NVARCHAR2(20) NOT NULL,
  UPDATED_DATE TIMESTAMP(6) NOT NULL,
  UPDATED_BY NVARCHAR2(255) NOT NULL,
  AUTOCREATED NUMBER(1,0) NOT NULL,

  CONSTRAINT "ATTENDANCEMONITORINGCHECKPOINT_PK" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX ATTENDANCEMONITORINGCHECKPOINT_POINT_ID_STUDENT_ID_UNIQUE ON ATTENDANCEMONITORINGCHECKPOINT(POINT_ID, STUDENT_ID);
CREATE INDEX ATTENDANCEMONITORINGCHECKPOINT_POINT_ID ON ATTENDANCEMONITORINGCHECKPOINT(POINT_ID);
CREATE INDEX ATTENDANCEMONITORINGCHECKPOINT_STUDENT_ID ON ATTENDANCEMONITORINGCHECKPOINT(STUDENT_ID);

CREATE TABLE ATTENDANCEMONITORINGCHECKPOINTTOTAL (
  STUDENT_ID NVARCHAR2(100) NOT NULL,
  SCHEME_ID NVARCHAR2(255) NOT NULL,
  UNRECORDED NUMBER(4,0) NOT NULL,
  AUTHORIZED NUMBER(4,0) NOT NULL,
  UNAUTHORIZED NUMBER(4,0) NOT NULL,
  ATTENDED NUMBER(4,0) NOT NULL,
  UPDATED_DATE TIMESTAMP(6) NOT NULL,

  CONSTRAINT "ATTENDANCEMONITORINGCHECKPOINTTOTAL_PK" PRIMARY KEY ("STUDENT_ID", "SCHEME_ID")
);