-- TAB-1765
alter table Department add ShortName nvarchar2(255);

-- Default data from web sign-on
set define off;
update Department set ShortName = 'AdsFab' where code = 'ad';
update Department set ShortName = 'CAS' where code = 'am';
update Department set ShortName = 'Ancillary Services' where code = 'an';
update Department set ShortName = 'Academic & Student Services' where code = 'ao';
update Department set ShortName = 'LDC' where code = 'ap';
update Department set ShortName = 'SHSS' where code = 'as';
update Department set ShortName = 'Student Careers & Skills' where code = 'cc';
update Department set ShortName = 'CEDAR' where code = 'cd';
update Department set ShortName = 'CLL' where code = 'ce';
update Department set ShortName = 'CTCCS' where code = 'cl';
update Department set ShortName = 'Classics' where code = 'cx';
update Department set ShortName = 'CSC' where code = 'cy';
update Department set ShortName = 'DARO' where code = 'dv';
update Department set ShortName = 'CEI' where code = 'ed';
update Department set ShortName = 'English' where code = 'en';
update Department set ShortName = 'CAL' where code = 'et';
update Department set ShortName = 'Film & TV Studies' where code = 'fi';
update Department set ShortName = 'HEFP' where code = 'fp';
update Department set ShortName = 'CSGR' where code = 'gr';
update Department set ShortName = 'NAGTY' where code = 'gy';
update Department set ShortName = 'Warwick Accommodation' where code = 'ho';
update Department set ShortName = 'Institute of Advanced Study' where code = 'ia';
update Department set ShortName = 'IGGY' where code = 'ig';
update Department set ShortName = 'WBS' where code = 'ib';
update Department set ShortName = 'IT Services' where code = 'in';
update Department set ShortName = 'IER' where code = 'ir';
update Department set ShortName = 'Cultural Policy Studies' where code = 'lp';
update Department set ShortName = 'MOAC' where code = 'mo';
update Department set ShortName = 'Comms Office' where code = 'om';
update Department set ShortName = 'PAIS' where code = 'po';
update Department set ShortName = 'CRER' where code = 're';
update Department set ShortName = 'Registrar''s Office' where code = 'ro';
update Department set ShortName = 'Theatre Studies' where code = 'th';
update Department set ShortName = 'RSS' where code = 'tt';
update Department set ShortName = 'Students'' Union' where code = 'us';
update Department set ShortName = 'VC''s Office' where code = 'vc';
update Department set ShortName = 'WMG' where code = 'wm';