create table attendancenote (
  ID NVARCHAR2(255) NOT NULL,
  STUDENT_ID NVARCHAR2(100) NOT NULL,
  UPDATEDDATE timestamp(6),
  UPDATEDBY nvarchar2(255) not null,
  NOTE nclob,
  ATTACHMENT_ID NVARCHAR2(255),
  DISCRIMINATOR NVARCHAR2(100) not null,
  PARENT_ID NVARCHAR2(255),

  CONSTRAINT "ATTENDANCENOTE_PK" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX IDX_AN_STUDENT_DISC_PARENT ON attendancenote(STUDENT_ID, DISCRIMINATOR, PARENT_ID);