CREATE TABLE ATTENDANCETEMPLATE
(	"ID" NVARCHAR2(250) NOT NULL,
  "CREATEDDATE" TIMESTAMP (6),
  "UPDATEDDATE" TIMESTAMP (6),
  "POINT_STYLE" NVARCHAR2(100) NOT NULL,
  "TEMPLATENAME" NVARCHAR2(255) NOT NULL,
  "POSITION" NUMBER(3,0),
  CONSTRAINT "ATTENDANCETEMPLATE_PK" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX IDX_AT_TEMPLATE_NAME ON ATTENDANCETEMPLATE(TEMPLATENAME);

CREATE TABLE ATTENDANCETEMPLATEPOINT (
  ID NVARCHAR2(255) NOT NULL,
  SCHEME_TEMPLATE_ID NVARCHAR2(255) NOT NULL,
  NAME NVARCHAR2(4000) NOT NULL,
  START_WEEK NUMBER(2,0) DEFAULT 0,
  END_WEEK NUMBER(2,0) DEFAULT 0,
  START_DATE TIMESTAMP(6),
  END_DATE TIMESTAMP(6),
  POINT_TYPE NVARCHAR2(100) NOT NULL,
  CREATED_DATE TIMESTAMP(6) NOT NULL,
  UPDATED_DATE TIMESTAMP(6) NOT NULL,
  CONSTRAINT "ATTENDANCETEMPLATEPOINT_PK" PRIMARY KEY ("ID")
);

CREATE INDEX AMP_TEMPLATE_SCHEME_ID ON ATTENDANCETEMPLATEPOINT(SCHEME_TEMPLATE_ID);