-- TAB-2112 StudyLevel table

CREATE TABLE STUDYLEVEL (

	CODE NVARCHAR2(20) NOT NULL,
	SHORTNAME NVARCHAR2(30),
	NAME NVARCHAR2(100),
  LASTUPDATEDDATE TIMESTAMP,
  HIB_VERSION NUMBER,

	CONSTRAINT "LEVEL_PK" PRIMARY KEY ("CODE")
);
