ALTER TABLE MONITORINGCHECKPOINT
ADD (
  student_id NVARCHAR2(100)
);

UPDATE MONITORINGCHECKPOINT
SET student_id = substr(MONITORINGCHECKPOINT.STUDENT_COURSE_DETAIL_ID,0,7)
WHERE student_id is null;

ALTER TABLE MONITORINGCHECKPOINT
MODIFY (
  student_id NVARCHAR2(100) not null
);

ALTER TABLE MONITORINGCHECKPOINT
MODIFY (
  STUDENT_COURSE_DETAIL_ID NVARCHAR2(250) null
);

create index idx_mcheckpoint_student_id on monitoringcheckpoint(student_id);