DROP INDEX AMCT_POINT_ID_SCHEME_ID_UNIQUE;

ALTER TABLE ATTENDANCEMONITORINGTOTAL
DROP (
  SCHEME_ID
);

ALTER TABLE ATTENDANCEMONITORINGTOTAL
ADD (
  DEPARTMENT_ID NVARCHAR2(255) NOT NULL,
  ACADEMICYEAR NUMBER(4,0) NOT NULL
);

CREATE UNIQUE INDEX AMCT_STUDENT_DEPT_YEAR_UNIQUE ON ATTENDANCEMONITORINGTOTAL(STUDENT_ID, DEPARTMENT_ID, ACADEMICYEAR);