-- TAB-3245
ALTER TABLE UPSTREAMASSIGNMENT
ADD (
  MARKSCODE nvarchar2(100)
);

CREATE TABLE GRADEBOUNDARY
(
  "ID" NVARCHAR2(250) NOT NULL,
  "MARKSCODE" NVARCHAR2(100) NOT NULL,
  "GRADE" NVARCHAR2(100) NOT NULL,
  "MINIMUMMARK" NUMBER(3,0) NOT NULL,
  "MAXIMUMMARK" NUMBER(3,0) NOT NULL,
  CONSTRAINT "GRADEBOUNDARY_PK" PRIMARY KEY ("ID")
);

CREATE INDEX IDX_GRADEBOUNDARY_MARKSCODE ON GRADEBOUNDARY(MARKSCODE);

INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-ug-1', 'TABULA-UG', '1', '80', '100');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-ug-2', 'TABULA-UG', '1', '70', '79');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-ug-3', 'TABULA-UG', '21', '60', '69');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-ug-4', 'TABULA-UG', '22', '50', '59');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-ug-5', 'TABULA-UG', '3', '40', '49');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-ug-6', 'TABULA-UG', 'F', '0', '39');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-pg-1', 'TABULA-PG', 'A+', '80', '100');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-pg-2', 'TABULA-PG', 'A', '70', '79');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-pg-3', 'TABULA-PG', 'B', '60', '69');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-pg-4', 'TABULA-PG', 'C', '50', '59');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-pg-5', 'TABULA-PG', 'D', '40', '49');
INSERT INTO "GRADEBOUNDARY" VALUES ('tabula-pg-6', 'TABULA-PG', 'E', '0', '39');