--- TAB-3874

DROP INDEX IDX_GRANTEDROLE_TYPE;
CREATE UNIQUE INDEX IDX_GRANTEDROLE_TYPE ON GRANTEDROLE(scope_type, scope_id, custom_role_id, builtInRoleDefinition);

DROP INDEX IDX_GRANTEDPERMISSION_TYPE;
CREATE UNIQUE INDEX IDX_GRANTEDPERMISSION_TYPE ON GRANTEDPERMISSION(scope_type, scope_id, permission, overrideType);
