-- TAB-4188

CREATE TABLE UPSTREAMMODULELIST (
  CODE NVARCHAR2(255) NOT NULL,
  ACADEMICYEAR NUMBER(4,0) NOT NULL,
  ROUTECODE NVARCHAR2(20) NOT NULL,
  YEAROFSTUDY NUMBER(2,0) NOT NULL,
  CONSTRAINT UPSTREAMMODULELIST_PK PRIMARY KEY (CODE)
);

CREATE TABLE UPSTREAMMODULELISTENTRY (
  ID NVARCHAR2(255) NOT NULL,
  LISTCODE NVARCHAR2(255) NOT NULL,
  MATCHSTRING NVARCHAR2(255) NOT NULL,
  CONSTRAINT UPSTREAMMODULELISTENTRY_PK PRIMARY KEY (ID)
);

CREATE INDEX IDX_UPSTREAMMODULELISTENTRY ON UPSTREAMMODULELISTENTRY(LISTCODE);