-- TAB-4052
CREATE TABLE COURSEYEARWEIGHTING
(
  ID NVARCHAR2(255) NOT NULL,
  COURSECODE NVARCHAR2(255) NOT NULL,
  ACADEMICYEAR NUMBER(4,0) NOT NULL,
  YEAROFSTUDY NUMBER(2,0) NOT NULL,
  WEIGHTING DECIMAL(4,3) NOT NULL,
  CONSTRAINT COURSEYEARWEIGHTING_PK PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_COURSEYEARWEIGHTING_UNIQUE ON COURSEYEARWEIGHTING(COURSECODE, ACADEMICYEAR, YEAROFSTUDY);