-- TAB-4197

CREATE TABLE UPSTREAMROUTERULE (
  ID NVARCHAR2(255) NOT NULL,
  ACADEMICYEAR NUMBER(4,0) NULL, -- If null apply to every year
  ROUTECODE NVARCHAR2(20) NOT NULL,
  YEAROFSTUDY NUMBER(2,0) NOT NULL,
  CONSTRAINT UPSTREAMROUTERULE_PK PRIMARY KEY (ID)
);

CREATE TABLE UPSTREAMROUTERULEENTRY (
  ID NVARCHAR2(255) NOT NULL,
  RULE_ID NVARCHAR2(255) NOT NULL,
  LISTCODE NVARCHAR2(255) NOT NULL,
  MIN_CATS NUMBER(5,2) NULL,
  MAX_CATS NUMBER(5,2) NULL,
  MIN_MODULES NUMBER(3,0) NULL,
  MAX_MODULES NUMBER(3,0) NULL,
  CONSTRAINT UPSTREAMROUTERULEENTRY_PK PRIMARY KEY (ID)
);

CREATE INDEX IDX_UPSTREAMROUTERULEENTRY ON UPSTREAMROUTERULEENTRY(RULE_ID);

INSERT INTO UPSTREAMMODULELIST VALUES ('ALLMODULES', 1000, 'NONE', 0);
INSERT INTO UPSTREAMMODULELISTENTRY VALUES ('ALLMODULES', 'ALLMODULES', '*');