--TAB-4640
INSERT INTO USERGROUPINCLUDE (GROUP_ID, USERCODE)
  SELECT GROUP_ID, USERCODE FROM USERGROUPSTATIC WHERE GROUP_ID IN (
    SELECT MEMBERSGROUP_ID FROM DEPARTMENTSMALLGROUPSET WHERE ACADEMICYEAR < 2016
  ) AND USERCODE NOT IN (
    SELECT USERCODE FROM USERGROUPEXCLUDE WHERE USERGROUPEXCLUDE.GROUP_ID = USERGROUPSTATIC.GROUP_ID
  ) AND USERCODE NOT IN (
    SELECT USERCODE FROM USERGROUPINCLUDE WHERE USERGROUPINCLUDE.GROUP_ID = USERGROUPSTATIC.GROUP_ID
  );
DELETE FROM USERGROUPSTATIC WHERE GROUP_ID IN (
  SELECT MEMBERSGROUP_ID FROM DEPARTMENTSMALLGROUPSET WHERE ACADEMICYEAR < 2016
);
UPDATE DEPARTMENTSMALLGROUPSET SET MEMBER_QUERY = NULL WHERE ACADEMICYEAR < 2016;