--- TAB-4335

alter table MEMBERNOTE add (
  DISCRIMINATOR varchar(13) default 'note' not null,
  START_DATE TIMESTAMP(6),
  END_DATE TIMESTAMP(6)
);

create INDEX IDX_MEMBERNOTE_DISCRIMINATOR on MEMBERNOTE("DISCRIMINATOR");