-- TAB-4884

CREATE TABLE NORMALCATSLOAD (
  ID NVARCHAR2(255) NOT NULL,
  ACADEMICYEAR NUMBER(4,0) NOT NULL,
  ROUTECODE NVARCHAR2(20) NOT NULL,
  YEAROFSTUDY NUMBER(2,0) NOT NULL,
  NORMALLOAD NUMBER(5,2) NOT NULL,
  CONSTRAINT NORMALCATSLOAD_PK PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_NORMALCATSLOAD_UNIQUE ON NORMALCATSLOAD(ACADEMICYEAR, ROUTECODE, YEAROFSTUDY);