ALTER TABLE MARKINGWORKFLOW MODIFY (ACADEMICYEAR NULL);

CREATE TABLE MARKINGWORKFLOWYEARS (
  WORKFLOW_ID NVARCHAR2(255) NOT NULL,
  ACADEMICYEAR NUMBER(4,0) NOT NULL
);
CREATE UNIQUE INDEX "MARKINGWORKFLOWYEARS_PK" ON MARKINGWORKFLOWYEARS(WORKFLOW_ID, ACADEMICYEAR);
CREATE INDEX IDX_MARKINGWORKFLOWYEARS_WF on MARKINGWORKFLOWYEARS(WORKFLOW_ID);
ALTER TABLE MARKINGWORKFLOWYEARS ADD CONSTRAINT MARKINGWORKFLOWYEARS_WF_FK FOREIGN KEY (WORKFLOW_ID) REFERENCES MARKINGWORKFLOW;

-- POST DEPLOY

ALTER TABLE MARKINGWORKFLOW SET UNUSED COLUMN ACADEMICYEAR;
ALTER TABLE MARKINGWORKFLOW DROP UNUSED COLUMNS;