-- TAB-5043
update STUDENTCOURSEYEARDETAILS
set ENROLLEDORCOMPLETED = 0
where
  (ENROLMENTSTATUSCODE like '1%' or ENROLMENTSTATUSCODE like '2%') and
  SCJCODE not in (
    select SCJCODE from STUDENTCOURSEDETAILS where REASONFORTRANSFERCODE like 'S%'
  );
