ALTER TABLE EXTENSION ADD ( REASON_NCLOB NCLOB );

UPDATE EXTENSION SET REASON_NCLOB = REASON;
COMMIT;

ALTER TABLE EXTENSION RENAME COLUMN REASON to REASON_OLD;

ALTER TABLE EXTENSION RENAME COLUMN REASON_NCLOB to REASON;
