CREATE TABLE MARKINGDESCRIPTOR (
  ID            NVARCHAR2(255) NOT NULL,
  DISCRIMINATOR CHAR(1)        NOT NULL,
  DEPARTMENT_ID NVARCHAR2(255),
  MIN_MARK      INT            NOT NULL,
  MAX_MARK      INT            NOT NULL,
  TEXT          NCLOB          NOT NULL,
  CONSTRAINT MARKINGDESCRIPTOR_PK PRIMARY KEY (ID)
);

CREATE INDEX IDX_MARKINGDESCRIPTOR_DEPARTMENT
  ON MARKINGDESCRIPTOR (DEPARTMENT_ID);

