<#escape x as x?html>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<style type="text/css">
		@page {
			@bottom-center {
				content: "Page " counter(page);
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 10px;
			}
		}
		@page :first {
			@bottom-center {
				content: "";
			}
		}

		body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 12px; }
		h1 { font-size: 20px; color: #7030a0; font-weight: bold; }
		h2 { font-size: 18px; color: #7030a0; font-weight: bold; }
		h3 { font-size: 14px; color: #000000; font-weight: bold; }
		p { margin-top: 0; }
		table { border-collapse: collapse; width: 100%; margin-bottom: 1em; }
		th { border: 1px solid black; padding: 8px 8px; font-size: 12px; font-weight: bold; background: #e5dfec; }
		td { border: 1px solid black; padding: 8px 8px; font-size: 10px; font-weight: bold; background: #f2f2f2; width: 1px; white-space: nowrap; vertical-align: top; }
		td + td { font-size: 10px; font-weight: normal; background: white; width: auto; white-space: normal; }

		.cover { page-break-after: always; text-align: center; }
		.cover h1 { padding-top: 200px; }

		.page { page-break-after: always; }
		table, .point, .summary-department, .event, .assignment { page-break-inside: avoid; }
	</style>
</head>
<body>
	<#assign terms = ["Pre-term vacation", "Autumn", "Christmas vacation", "Spring", "Easter vacation", "Summer", "Summer vacation"] />

	<#-- COVER SHEET -->
	<div class="cover">
		<h1 style="font-size: 24px;">Tabula Profile export</h1>
		<h3 style="font-size: 18px;">${student.fullName} - ${student.universityId}</h3>
		<h3 style="font-size: 18px;">Academic year ${academicYear.toString}</h3>
		<p><strong>Generated by: </strong>${user.fullName}</p>
		<p>${.now?string("short")}</p>
	</div>

	<div class="page">
		<h1>Profile</h1>

		<h2>Identity</h2>

		<table>
			<tbody>
				<tr>
					<td>Official name</td>
					<td>${student.officialName}</td>
				</tr>
				<tr>
					<td>Preferred name</td>
					<td>${student.fullName}</td>
				</tr>
				<#if student.gender??>
					<tr>
						<td>Gender</td>
						<td>${student.gender.description}</td>
					</tr>
				</#if>
				<#if student.nationality??>
					<tr>
						<td>Nationality</td>
						<td>
							<@fmt.nationality student.nationality!'Unknown' />
							<#if student.secondNationality??>
								and <@fmt.nationality student.secondNationality />
							</#if>
						</td>
					</tr>
				</#if>
				<#if student.disability?? && student.disability.reportable!false>
					<tr>
						<td>Disability</td>
						<td>${student.disability.definition}</td>
					</tr>
				</#if>
				<#if student.hasTier4Visa?? && student.casUsed??>
					<tr>
						<td>Tier 4 requirements</td>
						<td>
							<#if student.casUsed && student.hasTier4Visa>
								Yes
							<#elseif !student.casUsed && !student.hasTier4Visa>
								No
							<#else>
								Contact the Immigration Service
							</#if>
						</td>
					</tr>
				</#if>
				<#if student.email??>
					<tr>
						<td>Warwick email</td>
						<td>${student.email}</td>
					</tr>
				</#if>
				<#if student.homeEmail??>
					<tr>
						<td>Alternative email</td>
						<td>${student.homeEmail}</td>
					</tr>
				</#if>
				<#if student.mobileNumber??>
					<tr>
						<td>Mobile phone</td>
						<td>${phoneNumberFormatter(student.mobileNumber)}</td>
					</tr>
				</#if>
				<#if student.universityId??>
					<tr>
						<td>University ID</td>
						<td>${student.universityId}</td>
					</tr>
				</#if>
				<#if student.userId??>
					<tr>
						<td>Username</td>
						<td>${student.userId}</td>
					</tr>
				</#if>
				<#if student.homeDepartment??>
					<tr>
						<td>Home department</td>
						<td>${student.homeDepartment.name}</td>
					</tr>
				</#if>
			</tbody>
		</table>

		<h2>Course</h2>

		<#list courseData as course>
			<table>
				<tbody>
					<tr>
						<td>Course</td>
						<td>
							${course.courseName} ${course.courseCode}
							${course.beginYear} - ${course.endYear}
						</td>
					</tr>
					<#if course.departmentName??>
						<tr>
							<td>Department</td>
							<td>
								${course.departmentName}
								(${course.departmentCode})
							</td>
						</tr>
					</#if>
					<#if course.degreeType??>
						<tr>
							<td>UG/PG</td>
							<td>${course.degreeType}</td>
						</tr>
					</#if>
					<#if course.awardName??>
						<tr>
							<td>Intended award</td>
							<td>${course.awardName}</td>
						</tr>
					</#if>
					<#if course.modeOfAttendance??>
						<tr>
							<td>Attendance</td>
							<td>${course.modeOfAttendance}</td>
						</tr>
					</#if>
					<#if course.statusOnCourse??>
						<tr>
							<td>Status on course</td>
							<td>${course.statusOnCourse}</td>
						</tr>
					</#if>
					<#if course.endDate??>
						<tr>
							<td>End date</td>
							<td>${course.endDate}</td>
						</tr>
					</#if>
					<#if course.expectedEndDate??>
						<tr>
							<td>Expected end date</td>
							<td>${course.expectedEndDate}</td>
						</tr>
					</#if>
					<#if course.routeName??>
						<tr>
							<td>Route</td>
							<td>
								${course.routeName}
								(${course.routeCode})
							</td>
						</tr>
					</#if>
					<#if course.yearOfStudy??>
						<tr>
							<td>Study block or year</td>
							<td>${course.yearOfStudy}</td>
						</tr>
					</#if>
					<#if course.hasCurrentEnrolment && course.levelCode??>
						<tr>
							<td>Current course level</td>
							<td>
								${course.levelCode} (${course.levelName})
							</td>
						</tr>
					</#if>
					<#if course.sprCode??>
						<tr>
							<td>Programme route code</td>
							<td>${course.sprCode}</td>
						</tr>
					</#if>
					<#if course.scjCode??>
						<tr>
							<td>Course join code</td>
							<td>${course.scjCode}</td>
						</tr>
					</#if>
				</tbody>
			</table>
		</#list>
	</div>

	<#macro memberNote note>
		<table>
			<tbody>
				<tr>
					<td>Title</td>
					<td>${note.title}</td>
				</tr>
				<tr>
					<td>Created</td>
					<td>${note.date}</td>
				</tr>
				<tr>
					<td>Note</td>
					<td>
						<#noescape>
							${note.noteHTML}
						</#noescape>
					</td>
				</tr>
				<tr>
					<td>Attachments</td>
					<td>
						<#if note.attachments?has_content>
							<ul>
							<#list note.attachments as attachment>
								<li>
									${attachment.id}-${attachment.name}
								</li>
							</#list>
							</ul>
						<#else>
							<em>No files attached.</em>
						</#if>
					</td>
				</tr>
			</tbody>
		</table>
	</#macro>

	<div class="page">
		<h1>Administrative notes</h1>

		<#if administrativeNotesData?has_content>
			<#list administrativeNotesData as note>
				<@memberNote note />
			</#list>
		<#else>
			<p>
				<em>No administrative notes found.</em>
			</p>
		</#if>
	</div>

	<div class="page">
		<h1>Extenuating circumstances</h1>

		<#if extenuatingCircumstancesData?has_content>
			<#list extenuatingCircumstancesData as note>
				<@memberNote note />
			</#list>
		<#else>
			<p>
				<em>No extenuating circumstances found.</em>
			</p>
		</#if>
	</div>

	<#-- SUMMARY -->
	<div class="page">
		<h1>Attendance Summary</h1>
		<#if !summary?keys?has_content><p><em>No monitoring points found.</em></p></#if>
		<#list summary?keys?sort as department>
			<div class="summary-department">
				<h3>Monitoring points for ${department}</h3>
				<table>
					<thead>
						<tr>
							<th>Term</th>
							<th>Attended</th>
							<th>Missed</th>
							<th>Authorised Absence</th>
						</tr>
					</thead>
					<tbody>
						<#list terms as term>
							<tr>
								<td>${term}</td>
								<#if summary[department][term]??>
									<td>${summary[department][term]["attended"]!0}</td>
									<td>${summary[department][term]["unauthorised"]!0}</td>
									<td>${summary[department][term]["authorised"]!0}</td>
								<#else>
									<td>0</td>
									<td>0</td>
									<td>0</td>
								</#if>
							</tr>
						</#list>
					</tbody>
				</table>
			</div>
		</#list>
	</div>

	<#-- POINTS -->
	<#macro pointInATerm points state term>
		<div class="page">
			<h2>${state} Monitoring Points, Term: ${term}</h2>

			<#list points?sort_by("startDate") as point>
				<div class="point">
					<h3>Monitoring Point Name: ${point.name}</h3>
					<table>
						<thead>
							<tr>
								<th>Criteria</th>
								<th>Details</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Monitoring Point Type</td>
								<td>${point.pointType}</td>
							</tr>
							<tr>
								<td>Monitoring Point Type Information</td>
								<td>${point.pointTypeInfo!"&nbsp;"}</td>
							</tr>
							<tr>
								<td>Start Date</td>
								<td>${point.startDate}</td>
							</tr>
							<tr>
								<td>End Date</td>
								<td>${point.endDate}</td>
							</tr>
							<tr>
								<td>Recorded By</td>
								<td>${point.recordedBy.fullName!""} (${point.recordedBy.userId!"unknown"})</td>
							</tr>
							<tr>
								<td>Last Recorded Date</td>
								<td>${point.recordedDate}</td>
							</tr>
							<#if point.attendanceNote??>
								<tr>
									<td>Attendance Note</td>
									<td>
										<p>Reason: ${point.attendanceNote.absenceType.description}</p>
										Comments: <br/>
										<#noescape>${point.attendanceNote.escapedNote}</#noescape>
									</td>
								</tr>
								<tr>
									<td>Attendance Note Attachment</td>
									<td>
										<#if point.attendanceNote.attachment?has_content>
											${point.attendanceNote.attachment.id}-${point.attendanceNote.attachment.name}
										<#else>
											None
										</#if>
									</td>
								</tr>
							<#else>
								<tr>
									<td>Attendance Note</td>
									<td>None</td>
								</tr>
								<tr>
									<td>Attendance Note Attachments</td>
									<td>None</td>
								</tr>
							</#if>

						</tbody>
					</table>
				</div>
			</#list>
		</div>
	</#macro>
	<#list groupedPoints?keys?sort as department>
		<div class="department">
			<h1>Monitoring points for ${department}</h1>
			<div class="state">
				<#if groupedPoints[department]["attended"]??>
					<#list terms as term>
						<#if groupedPoints[department]["attended"][term]??>
							<@pointInATerm groupedPoints[department]["attended"][term] "Attended" term />
						</#if>
					</#list>
				</#if>
				<#if groupedPoints[department]["unauthorised"]??>
					<#list terms as term>
						<#if groupedPoints[department]["unauthorised"][term]??>
							<@pointInATerm groupedPoints[department]["unauthorised"][term] "Missed" term />
						</#if>
					</#list>
				</#if>
				<#if groupedPoints[department]["authorised"]??>
					<#list terms as term>
						<#if groupedPoints[department]["authorised"][term]??>
							<@pointInATerm groupedPoints[department]["authorised"][term] "Authorised Absence" term />
						</#if>
					</#list>
				</#if>
			</div>
		</div>
	</#list>

	<#-- ASSIGNMENTS -->
	<div class="page">
		<h1>Assignment submissions</h1>
		<#if !assignmentData?has_content><p><em>No assignments found.</em></p></#if>
		<#list assignmentData as assignment>
			<div class="assignment">
				<h3>${assignment.module} ${assignment.name}</h3>
			</div>
			<table>
				<tbody>
					<tr>
						<td>Submission deadline</td>
						<#if assignment.submissionDeadline?has_content>
							<td>${assignment.submissionDeadline}</td>
						<#else>
							<td>Open-ended assignment</td>
						</#if>
					</tr>
					<tr>
						<td>Submission date</td>
						<td>${assignment.submissionDate}</td>
					</tr>
					<tr>
						<td>Submitted files</td>
						<td>
							<ul>
								<#list assignment.attachments as attachment>
									<li>${attachment.id}-${attachment.name}</li>
								</#list>
							</ul>
						</td>
					</tr>
					<#if assignment.feedback?has_content>
						<#assign feedback = assignment.feedback>
						<tr>
							<td>Feedback publication date</td>
							<td>${feedback.releasedDate}</td>
						</tr>
						<tr>
							<td>Mark</td>
							<td>${feedback.mark!"No mark given"}</td>
						</tr>
						<tr>
							<td>Grade</td>
							<td>${feedback.grade!"No grade given"}</td>
						</tr>
						<tr>
							<td>Comments</td>
							<td>${feedback.comments!"No comments added"}</td>
						</tr>
						<tr>
							<td>File attachments</td>
							<td>
								<#if feedback.attachments?has_content>
									<ul>
										<#list feedback.attachments as attachment>
											<li>${attachment.id}-${attachment.name}</li>
										</#list>
									</ul>
								<#else>
									No feedback files attached.
								</#if>
							</td>
						</tr>
						<tr>
							<td>Adjustments</td>
							<td>
								<#if feedback.adjustments?has_content>
									<#list feedback.adjustments as adjustment>
										<table>
											<tbody>
												<tr>
													<td>Date</td>
													<td>${adjustment.date}</td>
												</tr>
												<tr>
													<td>Reason</td>
													<td>${adjustment.reason!"No reason given"}</td>
												</tr>
												<tr>
													<td>Adjusted mark</td>
													<td>${adjustment.mark!"No mark given"}</td>
												</tr>
												<tr>
													<td>Adjusted grade</td>
													<td>${adjustment.grade!"No grade given"}</td>
												</tr>
												<tr>
													<td>Comments</td>
													<td>${adjustment.comments!"No comments added"}</td>
												</tr>
											</tbody>
										</table>
									</#list>
								<#else>
									No adjustments have been made to this mark.
								</#if>
							</td>
						</tr>
					<#else>
						<tr>
							<td>Feedback publication date</td>
							<td>Feedback has not been published for this assignment.</td>
						</tr>
					</#if>
				</tbody>
			</table>
		</#list>
	</div>

	<#-- SMALL GROUP ATTENDANCE -->
	<div class="page">
		<h1>Small group event attendance</h1>
		<#if !smallGroupData?keys?has_content><p><em>No small group event attendance found.</em></p></#if>
		<#list smallGroupData?keys as eventId>
			<div class="event">
				<h3>${smallGroupData[eventId]?first.title}</h3>
				<p>
					${smallGroupData[eventId]?first.day}s
					<#if smallGroupData[eventId]?first.tutors?has_content><br />Tutors: ${smallGroupData[eventId]?first.tutors}</#if>
					<#if smallGroupData[eventId]?first.location?has_content><br />Location: ${smallGroupData[eventId]?first.location}</#if>
				</p>
				<table>
					<thead>
						<tr>
							<th>Week</th>
							<th>Attendance</th>
							<th>Attendance note</th>
						</tr>
					</thead>
					<tbody>
						<#list smallGroupData[eventId]?sort_by("week") as attendance>
							<tr>
								<td>${attendance.week}</td>
								<td>${attendance.state}</td>
								<#if attendance.attendanceNote?has_content>
									<td>
										<p>Reason: ${attendance.attendanceNote.absenceType.description}</p>
										Comments: <br/>
										<#noescape>${attendance.attendanceNote.escapedNote}</#noescape>
										<#if attendance.attendanceNote.attachment?has_content>
											<p>Attachment: ${attendance.attendanceNote.attachment.id}-${attendance.attendanceNote.attachment.name}</p>
										</#if>
									</td>
								<#else>
									<td>None</td>
								</#if>
							</tr>
						</#list>
					</tbody>
				</table>
			</div>
		</#list>
	</div>

	<#-- MEETINGS -->
	<div class="page">
		<h1>Meeting records</h1>
		<#if !meetingData?keys?has_content><p><em>No meetings found.</em></p></#if>
		<#list meetingData?keys as relationshipType>
			<div class="assignment">
				<h3>${relationshipType} meetings</h3>
			</div>
			<#list meetingData[relationshipType] as meeting>
				<table>
					<thead>
						<tr>
							<th>Criteria</th>
							<th>Details</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>${relationshipType}</td>
							<td>${meeting.agent}</td>
						</tr>
						<tr>
							<td>Meeting date</td>
							<td>${meeting.meetingDate}</td>
						</tr>
						<tr>
							<td>Title</td>
							<td>${meeting.title}</td>
						</tr>
						<tr>
							<td>Format</td>
							<td>${meeting.format}</td>
						</tr>
						<tr>
							<td>Description</td>
							<td><#noescape>${meeting.description!""}</#noescape></td>
						</tr>
					</tbody>
				</table>
			</#list>
		</#list>
	</div>
</body>
</html>
</#escape>