<@script "/static/js/scripts.js" />
<@script "/static/js/jquery-copyable.js" />
<@script "/static/js/jquery-biglist.js" />
<@script "/static/js/jquery-confirmmodal.js" />
<@script "/static/js/jquery-details.js" />
<@script "/static/js/jquery-collapsible.js" />
<@script "/static/js/jquery-tableform.js" />
<@script "/static/js/jquery-draganddrop.js" />
<@script "/static/js/jquery-expandingTable.js" />
<@script "/static/js/jquery.form.js" />
<@script "/static/js/jquery-filteredlist.js" />
<@script "/static/js/jquery-radiocontrolled.js" />
<@script "/static/js/jquery-scrolltofixed.js" />
<@script "/static/js/jquery-fixheaderfooter.js" />
<@script "/static/js/jquery.are-you-sure.js" />
<@script "/static/js/userpicker.js" />
<@script "/static/js/flexipicker.js" />
<@script "/static/js/ajax-popup.js" />
<@script "/static/js/app-comments.js" />
<@script "/static/js/select-deselect-checkboxes.js" />
<@script "/static/js/combo-typeahead.js" />
<@script "/static/js/map-popups.js" />