#!/bin/bash

ANT="ant -logger org.apache.tools.ant.listener.AnsiColorLogger"

if [[ "x" == "x$1" ]]; then
  echo "usage: run-test TestName"
  exit 1
else
  TESTNAME=$1
  if [[ $TESTNAME =~ .+Test ]]; then
    x=3
  else
    echo "Adding Test on the end..."
    TESTNAME="${TESTNAME}Test"
  fi
  echo "Running $TESTNAME"
fi

DIR="$(dirname "${BASH_SOURCE[0]}")/../../"

pushd $DIR > /dev/null
$ANT test -Dtest.name="$TESTNAME"
popd > /dev/null


