package uk.ac.warwick.courses.data.model
import javax.persistence.GeneratedValue
import org.hibernate.annotations.GenericGenerator
import javax.persistence.Id
import scala.reflect.BeanProperty

/**
 * Provides an autogenerated Hibernate property called "id".
 * Hibernate will generate a UUID when the entity is first saved.
 */
trait GeneratedId {
	@BeanProperty
	@Id 
	@GeneratedValue(generator="system-uuid") 
	@GenericGenerator(name="system-uuid", strategy="org.hibernate.id.UUIDGenerator")
	var id:String = null
}