<#escape x as x?html>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<style type="text/css">
		@page {
			@bottom-center {
				content: "Page " counter(page);
				font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 10px;
			}
		}
		@page :first {
			@bottom-center {
				content: "";
			}
		}

		body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 12px; }
		h1 { font-size: 20px; color: #7030a0; font-weight: bold; }
		h2 { font-size: 18px; color: #7030a0; font-weight: bold; }
		h3 { font-size: 14px; color: #000000; font-weight: bold; }
		p { margin-top: 0; }
		table { border-collapse: collapse; width: 100%; margin-bottom: 1em; }
		th { border: 1px solid black; padding: 8px 8px; font-size: 12px; font-weight: bold; background: #e5dfec; }
		td { border: 1px solid black; padding: 8px 8px; font-size: 10px; font-weight: bold; background: #f2f2f2; width: 1px; white-space: nowrap; vertical-align: top; }
		td + td { font-size: 10px; font-weight: normal; background: white; width: auto; white-space: normal; }

		div.cover { page-break-after: always; text-align: center; }
		div.cover h1 { padding-top: 200px; }

		div.summary, div.term, div.state, div.department, div.assignments, div.small-groups, div.meetings { page-break-after: always; }
		table, div.point, div.summary-department, div.event, div.assignment { page-break-inside: avoid; }
	</style>
</head>
<body>
	<#assign terms = ["Autumn", "Christmas vacation", "Spring", "Easter vacation", "Summer", "Summer vacation"] />

	<#-- COVER SHEET -->
	<div class="cover">
		<h1 style="font-size: 24px;">Profile export</h1>
		<h3 style="font-size: 18px;">${student.fullName} - ${student.universityId}</h3>
		<h3 style="font-size: 18px;">Academic year ${academicYear.toString}</h3>
		<p><strong>Generated by: </strong>${user.fullName}</p>
		<p>${.now?string("short")}</p>
	</div>

	<#-- SUMMARY -->
	<div class="summary">
		<h1>Attendance Summary</h1>
		<#if !summary?keys?has_content><p><em>No monitoring points found.</em></p></#if>
		<#list summary?keys?sort as department>
			<div class="summary-department">
				<h3>Monitoring points for ${department}</h3>
				<table>
					<thead>
						<tr>
							<th>Term</th>
							<th>Attended</th>
							<th>Missed</th>
							<th>Authorised Absence</th>
						</tr>
					</thead>
					<tbody>
						<#list terms as term>
							<tr>
								<td>${term}</td>
								<#if summary[department][term]??>
									<td>${summary[department][term]["attended"]!0}</td>
									<td>${summary[department][term]["unauthorised"]!0}</td>
									<td>${summary[department][term]["authorised"]!0}</td>
								<#else>
									<td>0</td>
									<td>0</td>
									<td>0</td>
								</#if>
							</tr>
						</#list>
					</tbody>
				</table>
			</div>
		</#list>
	</div>

	<#-- POINTS -->
	<#macro pointInATerm points state term>
		<div class="term">
			<h2>${state} Monitoring Points, Term: ${term}</h2>

			<#list points?sort_by("startDate") as point>
				<div class="point">
					<h3>Monitoring Point Name: ${point.name}</h3>
					<table>
						<thead>
							<tr>
								<th>Criteria</th>
								<th>Details</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Monitoring Point Type</td>
								<td>${point.pointType}</td>
							</tr>
							<tr>
								<td>Monitoring Point Type Information</td>
								<td>${point.pointTypeInfo!"&nbsp;"}</td>
							</tr>
							<tr>
								<td>Start Date</td>
								<td>${point.startDate}</td>
							</tr>
							<tr>
								<td>End Date</td>
								<td>${point.endDate}</td>
							</tr>
							<tr>
								<td>Recorded By</td>
								<td>${point.recordedBy.fullName!""} (${point.recordedBy.userId!"unknown"})</td>
							</tr>
							<tr>
								<td>Last Recorded Date</td>
								<td>${point.recordedDate}</td>
							</tr>
							<#if point.attendanceNote??>
								<tr>
									<td>Attendance Note</td>
									<td>
										<p>Reason: ${point.attendanceNote.absenceType.description}</p>
										Comments: <br/>
										<#noescape>${point.attendanceNote.escapedNote}</#noescape>
									</td>
								</tr>
								<tr>
									<td>Attendance Note Attachment</td>
									<td>
										<#if point.attendanceNote.attachment?has_content>
											${point.attendanceNote.attachment.id}-${point.attendanceNote.attachment.name}
										<#else>
											None
										</#if>
									</td>
								</tr>
							<#else>
								<tr>
									<td>Attendance Note</td>
									<td>None</td>
								</tr>
								<tr>
									<td>Attendance Note Attachments</td>
									<td>None</td>
								</tr>
							</#if>

						</tbody>
					</table>
				</div>
			</#list>
		</div>
	</#macro>
	<#list groupedPoints?keys?sort as department>
		<div class="department">
			<h1>Monitoring points for ${department}</h1>
			<div class="state">
				<#if groupedPoints[department]["attended"]??>
					<#list terms as term>
						<#if groupedPoints[department]["attended"][term]??>
							<@pointInATerm groupedPoints[department]["attended"][term] "Attended" term />
						</#if>
					</#list>
				</#if>
				<#if groupedPoints[department]["unauthorised"]??>
					<#list terms as term>
						<#if groupedPoints[department]["unauthorised"][term]??>
							<@pointInATerm groupedPoints[department]["unauthorised"][term] "Missed" term />
						</#if>
					</#list>
				</#if>
				<#if groupedPoints[department]["authorised"]??>
					<#list terms as term>
						<#if groupedPoints[department]["authorised"][term]??>
							<@pointInATerm groupedPoints[department]["authorised"][term] "Authorised Absence" term />
						</#if>
					</#list>
				</#if>
			</div>
		</div>
	</#list>

	<#-- ASSIGNMENTS -->
	<div class="assignments">
		<h1>Assignment submissions</h1>
		<#if !assignmentData?has_content><p><em>No assignments found.</em></p></#if>
		<#list assignmentData as assignment>
			<div class="assignment">
				<h3>${assignment.module} ${assignment.name}</h3>
			</div>
			<table>
				<tbody>
					<tr>
						<td>Submission deadline</td>
						<td>${assignment.submissionDeadline}</td>
					</tr>
					<tr>
						<td>Submission date</td>
						<td>${assignment.submissionDate}</td>
					</tr>
				</tbody>
			</table>
		</#list>
	</div>

	<#-- SMALL GROUP ATTENDANCE -->
	<div class="small-groups">
		<h1>Small group event attendance</h1>
		<#if !smallGroupData?keys?has_content><p><em>No small group event attendance found.</em></p></#if>
		<#list smallGroupData?keys as eventId>
			<div class="event">
				<h3>${smallGroupData[eventId]?first.title}</h3>
				<p>
					${smallGroupData[eventId]?first.day}s
					<#if smallGroupData[eventId]?first.tutors?has_content><br />Tutors: ${smallGroupData[eventId]?first.tutors}</#if>
					<#if smallGroupData[eventId]?first.location?has_content><br />Location: ${smallGroupData[eventId]?first.location}</#if>
				</p>
				<table>
					<thead>
						<tr>
							<th>Week</th>
							<th>Attendance</th>
							<th>Attendance note</th>
						</tr>
					</thead>
					<tbody>
						<#list smallGroupData[eventId]?sort_by("week") as attendance>
							<tr>
								<td>${attendance.week}</td>
								<td>${attendance.state}</td>
								<#if attendance.attendanceNote?has_content>
									<td>
										<p>Reason: ${attendance.attendanceNote.absenceType.description}</p>
										Comments: <br/>
										<#noescape>${attendance.attendanceNote.escapedNote}</#noescape>
										<#if attendance.attendanceNote.attachment?has_content>
											<p>Attachment: ${attendance.attendanceNote.attachment.id}-${attendance.attendanceNote.attachment.name}</p>
										</#if>
									</td>
								<#else>
									<td>None</td>
								</#if>
							</tr>
						</#list>
					</tbody>
				</table>
			</div>
		</#list>
	</div>

	<#-- MEETINGS -->
	<div class="meetings">
		<h1>Meeting records</h1>
		<#if !meetingData?keys?has_content><p><em>No meetings found.</em></p></#if>
		<#list meetingData?keys as relationshipType>
			<div class="assignment">
				<h3>${relationshipType} meetings</h3>
			</div>
			<#list meetingData[relationshipType] as meeting>
				<table>
					<thead>
						<tr>
							<th>Criteria</th>
							<th>Details</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>${relationshipType}</td>
							<td>${meeting.agent}</td>
						</tr>
						<tr>
							<td>Meeting date</td>
							<td>${meeting.meetingDate}</td>
						</tr>
						<tr>
							<td>Title</td>
							<td>${meeting.title}</td>
						</tr>
						<tr>
							<td>Format</td>
							<td>${meeting.format}</td>
						</tr>
						<tr>
							<td>Description</td>
							<td><#noescape>${meeting.description!""}</#noescape></td>
						</tr>
					</tbody>
				</table>
			</#list>
		</#list>
	</div>
</body>
</html>
</#escape>