-- HFC-363

CREATE TABLE MARKSCHEME
(
  ID NVARCHAR2(255) NOT NULL
, NAME NVARCHAR2(255) NOT NULL
, DEPARTMENT_ID NVARCHAR2(255)
, FIRSTMARKERS_ID NVARCHAR2(20)
, SECONDMARKERS_ID NVARCHAR2(20)
, CONSTRAINT MARKSCHEME_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

ALTER TABLE ASSIGNMENT
ADD (MARKSCHEME_ID NVARCHAR2(255) );

CREATE INDEX IDX_MARKSCHEME_DEPT ON MARKSCHEME (DEPARTMENT_ID);

